name: Safe Deploy React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '18.20'

      - name: Build React App
        run: |
          npm ci
          npm run build

      - name: Zip Build Directory
        run: zip -r build.zip build -x "*.git*" "*.github/*"

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build.zip"
          target: "/home/${{ secrets.EC2_USER }}/"

      - name: Safe Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            LIVE_DIR="/var/www/html/react"
            TEMP_DIR="/home/ubuntu/reacttemp"

            echo "Loading environment..."
            source ~/.bashrc || true
            source ~/.nvm/nvm.sh || true

            echo "Cleaning temp directory..."
            sudo rm -rf $TEMP_DIR
            sudo mkdir -p $TEMP_DIR

            echo "Unzipping build to temp..."
            sudo unzip -o /home/${{ secrets.EC2_USER }}/build.zip -d $TEMP_DIR
            sudo chmod -R 777 $TEMP_DIR

            echo "Deploying to live directory..."
            sudo rm -rf $LIVE_DIR
            sudo mv $TEMP_DIR/build $LIVE_DIR

            echo "✅ React App Deployed to $LIVE_DIR Successfully!"
